# Generated by Django 4.1.2 on 2023-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0002_remove_cliente_id_cliente_direccion_cliente_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('nombre', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=150)),
                ('precio', models.CharField(max_length=150)),
                ('stock', models.CharField(max_length=150)),
            ],
        ),
    ]
