# Generated by Django 4.1.2 on 2023-03-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
